/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package p2.zoobackendcrud.entities;

import java.io.Serializable;
import java.util.Collection;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import lombok.Data;

/**
 *
 * @author Agustín Pacheco
 */
@Entity
@Data
@Table(name = "zones")
public class Zone implements Serializable{
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id_zone", nullable = false)
    private Integer id;
    
    @Column(name = "name", nullable = false, length = 20)
    private String name;
    
    @Column(name = "extension", nullable = false)
    private Double extension;
    
    @ManyToMany(mappedBy = "coveredZones", fetch = FetchType.EAGER)
    Set<Itinerary> coveredItineraries;
    
    //null safe contructor
    public Zone(){
        coveredItineraries = new HashSet<>();
    }
    
    //All but id (autogenerated by db)
    public Zone(String name, Double extension) {
        this.name = name;
        this.extension = extension;
        coveredItineraries = new HashSet<>();
    }
    
    public void setCoveredItineraries(Collection<Itinerary> itineraries){
        if (itineraries == null) return;
        for (var i : itineraries.toArray()){
            System.out.println(i);
            coveredItineraries.add((Itinerary) i);
        }
    }
    
    @Override
    public String toString(){
        String s = "Zone id: " + id + ", name: " + name + ", Zone Extension: " + extension + " m2. ";
        if (!coveredItineraries.isEmpty()) {
            s += "This zone is covered by the following itineraries:";
            for (Itinerary i : coveredItineraries) {
                s += "\n\tItinerary Code:" + i.getCode() + " (id:" + i.getId() + ")";
            }
        }
        else{
            s += "This zone has no itinerary that covers it.";
        }
        return s;
    }
    
    @Override
    public int hashCode(){
        return Objects.hash(this.id, this.name);
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)    return true;
        if (obj == null)    return false;
        if (getClass() != obj.getClass())   return false;
        
        final Zone other = (Zone) obj;
        if (!Objects.equals(this.coveredItineraries, other.coveredItineraries)) return false;
        if (Objects.equals(this.id, other.getId()) 
                && (this.name == null ? other.getName() == null : this.name.equals(other.getName())) 
                && Objects.equals(this.extension, other.getExtension())) {
            
            for(Itinerary i: coveredItineraries){
                if (!(other.getCoveredItineraries().contains(i))) return false;
            }
                    
            return true;
        }
        return true;
    }
}
